### ISSUE TITLE
Migrate to Obj-C

### ISSUE THREAD

**Issue by perfaram** [fmorrow/SMBIOSParser#2]
Hey !
So, do you think it's ready enough for me to start translating, as it was intended ?

**Comment by perfaram** [comment]
Anything ?

**Comment by ghost** [comment]
Sorry Perceval, been a bit caught up with work and stuff! A very very busy
time unfortunately.

There's one minor bug to do with the parsing, but I've isolated that and
think I've got a fix on my macbook! Will give it a test and push that up,
and send you an email :)

**Comment by ghost** [comment]
Will tag this issue (#2) in the commit message - so when I push it should send you an alert by email.

**Comment by perfaram** [comment]
Thanks !
